name: meditrage_app
description: MediTriage Flutter App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

  
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  http: ^1.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/data/hospitals/

